###

@URL = "https://localhost:5000/"

@ACCESS_TOKEN = key
@BUNGIE_USER_ID = id
@CHARACTER_ID = id
@WEAPON_ID = id


###
GET https://localhost:5000
X-Access-Token: {{ACCESS_TOKEN}}
X-Bungie-UserId: {{BUNGIE_USER_ID}}


###
POST https://localhost:5000/characters/{{CHARACTER_ID}}/equipement/weapon/{{WEAPON_ID}}/transfert
Content-Type: application/json
X-Access-Token: {{ACCESS_TOKEN}}
X-Bungie-UserId: {{BUNGIE_USER_ID}}

{
    "character_id_pull_equipment": 2305843009331614287
}


###
POST https://localhost:5000/characters/{{CHARACTER_ID}}/equipement/weapon/{{WEAPON_ID}}/equip
Content-Type: application/json
X-Access-Token: {{ACCESS_TOKEN}}
X-Bungie-UserId: {{BUNGIE_USER_ID}}


###
POST https://localhost:5000/characters/{{CHARACTER_ID}}/equipement/weapon/{{WEAPON_ID}}/store
Content-Type: application/json
X-Access-Token: {{ACCESS_TOKEN}}
X-Bungie-UserId: {{BUNGIE_USER_ID}}


###
POST https://localhost:5000/characters/{{CHARACTER_ID}}/equipement/weapon/{{WEAPON_ID}}/retrieve
Content-Type: application/json
X-Access-Token: {{ACCESS_TOKEN}}
X-Bungie-UserId: {{BUNGIE_USER_ID}}

###